const Markers = [
  {
    site: "Coleman Lodge - Aldridge",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "WS9 8LZ",
    latitude: 52.6025,
    longitude: -1.9131,
  },
  {
    site: "Headley Lodge - Ashtead",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "KT21 2TP",
    latitude: 51.3085,
    longitude: -0.2981,
  },
  {
    site: "Oscar Lodge - Aylesbury",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "HP20 1FN",
    latitude: 51.8178,
    longitude: -0.8115,
  },
  {
    site: "Wessex Lodge - Bagshot",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "GU19 5HN",
    latitude: 51.3641,
    longitude: -0.6888,
  },
  {
    site: "Linden Lodge - Bicester",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "OX26 6GE",
    latitude: 51.8978,
    longitude: -1.1534,
  },
  {
    site: "Meadow Lodge - Billericay",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CM12 9FU",
    latitude: 51.6247,
    longitude: 0.4191,
  },
  {
    site: "Walmsley Place - Bishops Waltham",
    customer: "McCarthy and Stone",
    type: "GSHP",
    postcode: "SO32 1AG",
    latitude: 50.9553,
    longitude: -1.2133,
  },
  {
    site: "Fleur-de-Lis Bourne End",
    customer: "Lifestory",
    type: "GSHP",
    postcode: "SL8 5RU",
    latitude: 51.5779,
    longitude: -0.7115,
  },
  {
    site: "Alfred Lodge - Bridport",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "DT6 3JL",
    latitude: 50.7321,
    longitude: -2.7582,
  },
  {
    site: "Beeches Lodge - Burnham",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SL1 8AG",
    latitude: 51.5357,
    longitude: -0.6475,
  },
  {
    site: "Laurel Lodge - Carshalton",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SM5 2FQ",
    latitude: 51.3686,
    longitude: -0.1778,
  },
  {
    site: "Hudson Lodge - Cheam",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SM1 2DU",
    latitude: 51.3669,
    longitude: -0.1949,
  },
  {
    site: "Chelmer Lodge - Chelmsford",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CM2 0QL",
    latitude: 51.7322,
    longitude: 0.4782,
  },
  {
    site: "Lewis Carroll Lodge - Cheltenham",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "GL50 4FH",
    latitude: 51.895,
    longitude: -2.0694,
  },
  {
    site: "Harrington Lodge - Chichester",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "PO19 7BX",
    latitude: 50.8366,
    longitude: -0.7746,
  },
  {
    site: "St Andrews Lodge - Chippenham",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SN15 3HN",
    latitude: 51.4573,
    longitude: -2.1154,
  },
  {
    site: "Beecham Lodge - Cirencester",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "GL7 1TW",
    latitude: 51.7101,
    longitude: -1.966,
  },
  {
    site: "De Clare Lodge - Cowbridge",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CF71 7FR",
    latitude: 51.458,
    longitude: -3.3685,
  },
  {
    site: "50 Dukes Ride - Crowthorne",
    customer: "Lifestory",
    type: "GSHP",
    postcode: "GU14 7PN",
    latitude: 51.3538,
    longitude: -0.8351,
  },
  {
    site: "Keyes Lodge - Dartford",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BR6 0SD",
    latitude: 51.4421,
    longitude: 0.1932,
  },
  {
    site: "Goodwin Lodge - Deal",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CT14 6FL",
    latitude: 51.215,
    longitude: 1.3947,
  },
  {
    site: "Taylor Place - Dorking",
    customer: "Lifestory",
    type: "GSHP",
    postcode: "RH4 1GS",
    latitude: 51.2062,
    longitude: -0.3337,
  },
  {
    site: "Simmonds Lodge - Drayton",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "PO6 2JE",
    latitude: 50.8496,
    longitude: -1.0275,
  },
  {
    site: "McIndoe Lodge - East Grinstead",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "RH19 1FU",
    latitude: 51.0182,
    longitude: -0.033,
  },
  {
    site: "Allingham Lodge - Eastbourne",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BN21 1AF",
    latitude: 50.7693,
    longitude: 0.2916,
  },
  {
    site: "Charlotte Lodge - Eastleigh",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SO50 9AD",
    latitude: 50.9749,
    longitude: -1.3547,
  },
  {
    site: "Jefferies Lodge - Eltham",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SE9 2SU",
    latitude: 51.4585,
    longitude: 0.0461,
  },
  {
    site: "Cooper Lodge - Frinton",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CO13 9NH",
    latitude: 51.9311,
    longitude: 1.2455,
  },
  {
    site: "Weavers Lodge - Haverhill",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CB9 8AY",
    latitude: 52.0834,
    longitude: 0.439,
  },
  {
    site: "Rothesay Lodge - Highcliffe",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BH23 5FP",
    latitude: 50.7338,
    longitude: -1.7113,
  },
  {
    site: "Dovehouse Lodge - Hitchin",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SG5 2AU",
    latitude: 51.9433,
    longitude: -0.2699,
  },
  {
    site: "Moorhouse Lodge - Huntingdon",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "PE29 3FD",
    latitude: 52.3165,
    longitude: -0.1846,
  },
  {
    site: "Hubert Lodge - Hythe",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SO45 6EB",
    latitude: 50.8421,
    longitude: -1.3503,
  },
  {
    site: "Eleanor Lodge - Knowle",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "B93 0HT",
    latitude: 52.3681,
    longitude: -1.7377,
  },
  {
    site: "Hale Lodge - Littlehampton",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BN17 5ET",
    latitude: 50.8169,
    longitude: -0.5463,
  },
  {
    site: "Betjeman Lodge - Ludlow",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SY8 1DJ",
    latitude: 52.3695,
    longitude: -2.725,
  },
  {
    site: "Knights Lodge - Lymington",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SO41 9PB",
    latitude: 50.7592,
    longitude: -1.554,
  },
  {
    site: "Kings Lodge - Maidstone",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "ME14 1BG",
    latitude: 51.2725,
    longitude: 0.5217,
  },
  {
    site: "Peel Lodge - Marlow",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SL7 3FH",
    latitude: 51.5714,
    longitude: -0.7716,
  },
  {
    site: "Perran Lodge - Newquay",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "TR7 2RZ",
    latitude: 50.4182,
    longitude: -5.0751,
  },
  {
    site: "Atkins Lodge - Orpington",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BR6 0SD",
    latitude: 51.3741,
    longitude: 0.1002,
  },
  {
    site: "Beck Lodge - Park Gate",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SO31 1AJ",
    latitude: 50.8712,
    longitude: -1.2704,
  },
  {
    site: "Neville Lodge - Peacehaven",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BN10 7PD",
    latitude: 50.7926,
    longitude: 0.0015,
  },
  {
    site: "Dutton Lodge - Penrith",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CA11 8HT",
    latitude: 54.6634,
    longitude: -2.7525,
  },
  {
    site: "Heath Lodge - Pinner",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "HA5 5PB",
    latitude: 51.5939,
    longitude: -0.3828,
  },
  {
    site: "Fleur-de-lis Poole - Poole",
    customer: "Lifestory",
    type: "GSHP",
    postcode: "BH24 3SG",
    latitude: 50.7192,
    longitude: -1.8783,
  },
  {
    site: "Spitfire Lodge - Portswood",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "SO17 2LB",
    latitude: 50.9275,
    longitude: -1.3884,
  },
  {
    site: "Chiltern Lodge - Princes Ris",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "HP27 9HE",
    latitude: 51.7195,
    longitude: -0.8366,
  },
  {
    site: "Hadley Lodge - Quinton",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "B32 2TL",
    latitude: 52.4558,
    longitude: -1.9982,
  },
  {
    site: "Colebrooke Lodge - Reigate",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "RH2 8AX",
    latitude: 51.2372,
    longitude: -0.2076,
  },
  {
    site: "Fleur-de-Lis Sandhurst - Sandhurst",
    customer: "Lifestory",
    type: "GSHP",
    postcode: "GU47 0PR",
    latitude: 51.3447,
    longitude: -0.8007,
  },
  {
    site: "Sanderson Lodge - Selsdon",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CR2 8AY",
    latitude: 51.3351,
    longitude: -0.0609,
  },
  {
    site: "River View Lodge - Shepperton",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "TW17 9EQ",
    latitude: 51.3943,
    longitude: -0.4465,
  },
  {
    site: "Woolmans Lodge - Shirley",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "B90 3HL",
    latitude: 52.4066,
    longitude: -1.8252,
  },
  {
    site: "Lockyer Lodge - Sidford",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "EX10 9JU",
    latitude: 50.6945,
    longitude: -3.2358,
  },
  {
    site: "Beatrice Lodge - Sittingbourne",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "GL50 4DY",
    latitude: 51.3424,
    longitude: 0.7322,
  },
  {
    site: "Fern Court - Sketty",
    customer: "McCarthy and Stone",
    type: "GSHP",
    postcode: "BH24 3SG",
    latitude: 51.6173,
    longitude: -3.9837,
  },
  {
    site: "Park View - Southgate",
    customer: "Park View Care Home",
    type: "GSHP",
    postcode: "GL1 3ET",
    latitude: 51.8613,
    longitude: -2.2441,
  },
  {
    site: "Langton Lodge - Staines",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "TW18 3EB",
    latitude: 51.4339,
    longitude: -0.5196,
  },
  {
    site: "Stanley Lodge - Tattenham",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "KT18 7LX",
    latitude: 51.3105,
    longitude: -0.2456,
  },
  {
    site: "Riverain Lodge - Taunton",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "EX14 1NU",
    latitude: 51.0183,
    longitude: -3.1039,
  },
  {
    site: "Fitzford Lodge - Tavistock",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "PL19 8BU",
    latitude: 50.5476,
    longitude: -4.1457,
  },
  {
    site: "Yeats Lodge - Thame",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "OX9 3ZB",
    latitude: 51.7477,
    longitude: -0.9764,
  },
  {
    site: "Alexandra Lodge - Thornbury",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BS35 1HB",
    latitude: 51.6076,
    longitude: -2.5255,
  },
  {
    site: "St Giles Lodge - Tonbridge",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "TN10 3DJ",
    latitude: 51.2135,
    longitude: 0.2768,
  },
  {
    site: "Sachs Lodge - Torquay",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "TQ1 2QS",
    latitude: 50.467,
    longitude: -3.514,
  },
  {
    site: "Greenacres Lodge - Warlingham",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "CR2 8AY",
    latitude: 51.308,
    longitude: -0.0615,
  },
  {
    site: "Tatterton Lodge - Wetherby",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "LS22 7TE",
    latitude: 53.9271,
    longitude: -1.3863,
  },
  {
    site: "Fleur-de-Lis Wimborne - Wimborne",
    customer: "Lifestory",
    type: "GSHP",
    postcode: "BH24 1DG",
    latitude: 50.8005,
    longitude: -1.9451,
  },
  {
    site: "Fleur-de-lis Wokingham - Wokingham",
    customer: "Lifestory",
    type: "GSHP",
    postcode: "RG40 1BQ",
    latitude: 51.4116,
    longitude: -0.8357,
  },
  {
    site: "Trewin Lodge - Yate",
    customer: "Churchill Retirement Living",
    type: "GSHP",
    postcode: "BS37 4FX",
    latitude: 51.5446,
    longitude: -2.4088,
  },

  {
    site: "Lewis",
    customer: "Engineer",
    postcode: "TA1 4JB",
    latitude: 51.001582,
    longitude: -3.109523,
  },
  {
    site: "Jim",
    customer: "Engineer",
    postcode: "KT12 2LD",
    latitude: 51.375352,
    longitude: -0.423872,
  },
  {
    site: "Danny",
    customer: "Engineer",
    postcode: "EX4 8AW",
    latitude: 50.732957,
    longitude: -3.51158,
  },
  {
    site: "Owen",
    customer: "Engineer",
    postcode: "BS37 6DZ",
    latitude: 51.537462,
    longitude: -2.408256,
  },
  {
    site: "Richard",
    customer: "Engineer",
    postcode: "UB9 6AL",
    latitude: 51.588543,
    longitude: -0.509755,
  },
  {
    site: "James",
    customer: "Engineer",
    postcode: "LU5 6BH",
    latitude: 51.897265,
    longitude: -0.532257,
  },
  {
    site: "Aidan",
    customer: "Engineer",
    postcode: "DA16 1SP",
    latitude: 51.467723,
    longitude: 0.116653,
  },
  {
    site: "Omari",
    customer: "Engineer",
    postcode: "RG4 8BT",
    latitude: 51.482909,
    longitude: -0.954771,
  },
];

export default Markers;
